/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPackageDepsRouteImport } from './routes/api/package-deps'
import { Route as ApiOgRouteImport } from './routes/api/og'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPackageDepsRoute = ApiPackageDepsRouteImport.update({
  id: '/api/package-deps',
  path: '/api/package-deps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/og': typeof ApiOgRoute
  '/api/package-deps': typeof ApiPackageDepsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/og': typeof ApiOgRoute
  '/api/package-deps': typeof ApiPackageDepsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/og': typeof ApiOgRoute
  '/api/package-deps': typeof ApiPackageDepsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/og' | '/api/package-deps'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/og' | '/api/package-deps'
  id: '__root__' | '/' | '/api/og' | '/api/package-deps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiPackageDepsRoute: typeof ApiPackageDepsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/package-deps': {
      id: '/api/package-deps'
      path: '/api/package-deps'
      fullPath: '/api/package-deps'
      preLoaderRoute: typeof ApiPackageDepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiOgRoute: ApiOgRoute,
  ApiPackageDepsRoute: ApiPackageDepsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
