/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPackageDepsRouteImport } from './routes/api/package-deps'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPackageDepsRoute = ApiPackageDepsRouteImport.update({
  id: '/api/package-deps',
  path: '/api/package-deps',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/package-deps': typeof ApiPackageDepsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/package-deps': typeof ApiPackageDepsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/package-deps': typeof ApiPackageDepsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/package-deps'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/package-deps'
  id: '__root__' | '/' | '/api/package-deps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPackageDepsRoute: typeof ApiPackageDepsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/package-deps': {
      id: '/api/package-deps'
      path: '/api/package-deps'
      fullPath: '/api/package-deps'
      preLoaderRoute: typeof ApiPackageDepsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPackageDepsRoute: ApiPackageDepsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
